# Generated by Django 5.0.3 on 2026-01-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0003_project_remove_payment_project_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="agent_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
